### ISSUE TITLE
Other proteases

### ISSUE THREAD

**Issue by plyush1993** [jeffsocal/tidyproteomics#1]
Hello @jeffsocal 
Thank you for your great package! 😊

Is it possible to add some other proteases like Proteinase K, Pepsin at different pH, etc.?

**Comment by jeffsocal** [comment]
It is entirely possible. The underlying functions are part of another package jeffsocal/epfasta, where the protease is simply defined by a pattern expression. Which function are you referring to?

**Comment by plyush1993** [comment]
Thank you for your response @jeffsocal 
I mean fasta_peptides function.

**Comment by jeffsocal** [comment]
https://jeffsocal.github.io/tidyproteomics/reference/fasta_peptides.html
