### ISSUE TITLE
Duplicated rows in as.data.frame(shape ="wide")

### ISSUE THREAD

**Issue by tywang-tw** [jeffsocal/tidyproteomics#10]
I noticed that the duplicated rows happened due to the MBR column, can you please fix and make it as one row? Perhaps include the argument to drop the unwanted columns? Thanks!

example:
`hela_proteins %>% as.data.frame(shape="wide") %>% filter(protein == 'A0A024R1R8')`

**Comment by jeffsocal** [comment]
Nice catch. I fixed this issue with version 1.5.10.
