### ISSUE TITLE
Fail to install tidyproteomics package

### ISSUE THREAD

**Issue by Isabel-ql** [jeffsocal/tidyproteomics#13]
Hi, 

I'd like to analyse my mass spec data with tidyproteomic package in R, however, I could't install the package. The error says that dependency 'Biostrings' is not available for package 'tidyproteomics'. See the screenshot below. Could anybody help to solve this problem? Thank you very much!

Best,
Qun 
<img width="612" alt="Screenshot 2023-12-11 at 18 33 49" src="https://github.com/jeffsocal/tidyproteomics/assets/65905482/4894a9eb-7ae8-414b-9cdf-9eed6b2bdfe5">

**Comment by jeffsocal** [comment]
No worries. You need to install the Biostrings Packages. Use the following code snip to install the Bioconductor package manager, then the three packages you need. Also outlined on the documentation page, link below.

```
install.packages("BiocManager")
BiocManager::install(c("limma","qvalue","fgsea"))

```

https://jeffsocal.github.io/tidyproteomics/index.html#installation

**Comment by Isabel-ql** [comment]
Hi!

Yes, I installed Biostrings, and the other three packages from Bioconductor package manager, and it works now!

Thanks very much!

Best,
Qun

From: Jeff Jones ***@***.***>
Reply to: jeffsocal/tidyproteomics ***@***.***>
Date: Monday, 11 December 2023 at 19:33
To: jeffsocal/tidyproteomics ***@***.***>
Cc: "Qun Liu (JIC)" ***@***.***>, Author ***@***.***>
Subject: Re: [jeffsocal/tidyproteomics] Fail to install tidyproteomics package (Issue #13)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

No worries. You need to install the Biostrings Packages. Use the following code snip to install the Bioconductor package manager, then the three packages you need. Also outlined on the documentation page, link below.

install.packages("BiocManager")

BiocManager::install(c("limma","qvalue","fgsea"))



https://jeffsocal.github.io/tidyproteomics/index.html#installation
