### ISSUE TITLE
Export the protein list in venn diagram

### ISSUE THREAD

**Issue by tywang-tw** [jeffsocal/tidyproteomics#14]
Hi Jeff, Can you add the function to export the protein list (with annotation) from venn diagram or euler in tidyproteomics? Thanks!

**Comment by jeffsocal** [comment]
Thanks for the suggestion. I have added a new function `intersection()` in the version 1.7.0 that allows you to subset the data down to the proteins defined in a Venn segment. A description can be found here https://jeffsocal.github.io/tidyproteomics/articles/extracting.html.
