### ISSUE TITLE
Error in Imputation using impute.knn in matix method

### ISSUE THREAD

**Issue by tywang-tw** [jeffsocal/tidyproteomics#18]
Hi Jeff,

I noticed that an error occurred in impute() when using "impute.knn" with matix method, see below:

> rdata <- hela_proteins
> library(impute)
> rdata %>% impute(.function = impute.knn, method = 'matrix')
Error in .function(as.matrix(this_matrix), cores = cores) :  (data, k = 10, rowmax = 0.5, colmax = 0.8, maxp = 1500, rng.seed = 362436069) { r…
  unused argument (cores = cores)
✖ Imputing by matrix using the function base::quote function (data, k = 10, rowmax = 0.5, colmax = 0.8, maxp = 1500, rng.seed = 362436069) { r…

Could you please resolve it? Thank you.

**Comment by jeffsocal** [comment]
Thank you for pointing this out, my documentation was insufficient here.
 
The R package in `bioconductor::impute`, allows for the popular imputation method KNN. The generalized impute function for the method matrix assumes the underlying function is multithreaded, as is the impute.randomforest method. Therefore, to make any function operable, you need to make a wrapper function to allow for the `cores` variable to be accepted. In addition, the impute package returns an incompatible data object, that you must convert to a `matrix` - fortunately, the impute package’s data object contains the matrix in `$data`. See the article on [imputing with a matrix](https://jeffsocal.github.io/tidyproteomics/articles/imputing.html#using-matrix).
