### ISSUE TITLE
Import MaxQuant proteinGroups.txt

### ISSUE THREAD

**Issue by emortie** [jeffsocal/tidyproteomics#2]
When I want to import the proteinGroups.txt file provided here, all replicates are numbered 1. How can I adjust this in such a way that this is also been taken into account in the data_prot$quantitative?

**Comment by jeffsocal** [comment]
You will need to use the `reassign()` function. Replicates are automatically assigned such that they are always numbered 1..n, depending on the sample name(s). See the example below.

library(tidyverse)
library(tidyproteomics)

d_pro <- "~/Local/data/tidyproteomics/MaxQuant_1.6.10.43/proteinGroups.txt" |> 
  import("MaxQuant", "proteins") |> 
  reassign(sample %like% "ctrl", .replace = "ctrl") |> 
  reassign(sample %like% "p97_kd", .replace = "p97_kd")
