### ISSUE TITLE
Proteome Discoverer - Error in `tidyr::pivot_longer()`: `cols` must select at least one column.

### ISSUE THREAD

**Issue by eschen42** [jeffsocal/tidyproteomics#4]
# What happened?

I tried to read ProteomeDiscoverer 3.0 results and got
```
Error in `tidyr::pivot_longer()`:
 `cols` must select at least one column.
```

I got this error whether I 
- either tried to open the XLSX exported by Proteome Discoverer 3.0
- or exported the Proteins.txt file, imported into Excel, and saved as XLSX

I have previously been successful with the second approach given other data exported by PD, but I don't know what version was used then.

# What did I expect to happen?

I was hoping to import without incident

# Why am I submitting this issue?

I cannot (yet) glean enough information from the error message to identify what action to take to resolve this error.

# What might a successful resolution look like?

An error message specifying exactly what I need to do to resolve the issue.  I realize that this is an immensely heavy lift and will not be offended if you have to close the issue with a resolution that this will not be "fixed".

**Comment by jeffsocal** [comment]
Would you be willing to send the data file to my caltech email for testing? I can then fix your specific issue and attempt to build a more thoughtful error catch.

**Comment by eschen42** [comment]
> Would you be willing to send the data file to my caltech email for testing? I can then fix your specific issue and attempt to build a more thoughtful error catch.

Awesome. Thank you!  File sent.

**Comment by jeffsocal** [comment]
Thanks for sending the file along. There were two issues with the exported data file we discovered offline; 1) the file from ProteomeDiscoverer was nested (both proteins and peptides were exported as Level 1 and 2, respectively) which is difficult to parse; 2) the raw "Abundance: .." for each sample were not exported, instead "Abundances (Grouped): .." and "Abundance Ratio: ..". I will be updating the import documentation to advise on this issue.
