### ISSUE TITLE
num_peptides, num_unique peptides does not import properly MaxQuant

### ISSUE THREAD

**Issue by TARobison** [jeffsocal/tidyproteomics#5]
When importing proteinGroups.txt, I get NA values for all num_peptides, num_unique_peptides. This is not the case for num_psms, however. I have tried modifying the MaxQuant_proteins.tsv with no effect. Any advice would be appreciated

**Comment by jeffsocal** [comment]
Would you be willing to send along the file or a sample file I can examine? You can email me at the publication's corresponding author.

**Comment by jeffsocal** [comment]
Thanks for pointing this out, I need to update the import definition to allow for the counts to register - this is a bug. I will push an update shortly.
