### ISSUE TITLE
please review possible `.p.adjust` parameter for enrichments

### ISSUE THREAD

**Issue by eschen42** [jeffsocal/tidyproteomics#6]
The `.p.adjust` parameter is passed to and used by `expression_test`

> https://github.com/search?q=repo%3Ajeffsocal%2Ftidyproteomics+.p.adjust&type=code

but not by `analysis_enrichment_*`

> https://github.com/search?q=repo%3Ajeffsocal%2Ftidyproteomics+p.adjust&type=code

- If this is not an oversight, could you please add an explanation of why "holm" is an appropriate method for enrichment analysis?
- If this is an oversight, could you add a `.p.adjust` parameter for the enrichment analyses?

Thank you.

**Comment by jeffsocal** [comment]
Thanks for highlighting an often overlooked topic. On the surface this is an oversight, but it could be better documented. Both expression and enrichment yield adjusted p-values. I feel that for the expression test, whereby hundreds or thousands of univariate comparisons are being made, multiple test correction is mandatory, and easily subjected to user input. On the other hand, the multivariate comparisons being made by enrichment analysis (GSEA, Wilcoxon) are not. In the latter case, GSEA already provides an adjusted p.value, and the implemented Wilcoxon utilizes the straightforward Benjamin-Hochberg adjustment. In both methods, the p-values and adjusted p-values are provided such that any researcher could re-calculate an adjusted p-value based on their method of choice.*

*Bender, Ralf, and Stefan Lange. 2001. “Adjusting for Multiple Testing—when and How?” Journal of Clinical Epidemiology 54: 343–49.
