### ISSUE TITLE
Novice question

### ISSUE THREAD

**Issue by TaylorFerg234** [jeffsocal/tidyproteomics#7]
Hi Jeff, I'm super interested in running Tidyproteomics package to visualize some of my data however I've run into a bit of a snag at the first hurdle. I'm currently running the most up to date version of R studio (2023.09.1) and R (R 4.3.1) however when I run the installation codes it outlines that 'tidyproteomic' is not available fo this version of R. I'm a bit of a novice so forgive me if there is a simple answer to this question, but does this code have to be run via a specific version of R/R studio? Thanks in advance!

**Comment by jeffsocal** [comment]
This package incorporates enough dependencies that I am not able at this time to submit to CRAN. Therefor a different route is needed to install the package. Follow the instructions in the documentation and you should be just fine. 
https://jeffsocal.github.io/tidyproteomics/#installation
