### ISSUE TITLE
Using a user-defined function for NA value imputing

### ISSUE THREAD

**Issue by micwij** [jeffsocal/tidyproteomics#8]
Hi,
Thanks for making this great package!

I have some issues using a custom function for value imputation.
Let's say I want to use half of the minimum of other values and would write a function like:

 `halfmin <- function(x, na.rm = T){
    0.5*base::min(x, na.rm = na.rm)
  }`
and then run the imputation as :
`imp <- rdata %>% 
  impute(.function = halfmin )`

I get the error:
Error in impute_function_str[length(impute_function_str)] : 
  object of type 'symbol' is not subsettable

I assume this is related to

`data$operations <- append(data$operations, glue::glue("Missing values imputed by '{method}' samples via '{impute_function_str[length(impute_function_str)]}' group_by_sample '{group_by_sample}'."))
`

in the impute function. I tried to figure out how this works and if understand it correctly, this just takes the name of the function without the namespace e.g. "min" from "base::min" and this might be why it does not work with a function defined in the global environment, but maybe I also need to write the function in a different way. I also noticed when using the default by not defining a function (i.e. base::min) it prints:
Imputing by row using the function ::, base, and min, so maybe it is also possible to split this that it only shows the actual function name.

**Comment by jeffsocal** [comment]
Interesting ... the use of the function is successful, and as you pointed out it fails when recording the event in the log. This was an attempt to simplify the documentation aspect by only recording the name of the function using base::substitute() .. I have now replaced that with the more verbose base::enquote() and pushed out version 1.5.9. Thank you for your input, doing so makes the software better.
