### ISSUE TITLE
Add abundance value to expression table

### ISSUE THREAD

**Issue by tywang-tw** [jeffsocal/tidyproteomics#9]
Can you please add the abundance to the expression table output? I'd like to have this function to make the boxplot of the individual abundances. Thanks!

**Comment by jeffsocal** [comment]
That could be an option .. maybe for later release. In the meantime use the following example as a way to get what you are looking for:
```
tbl_expression <- hela_proteins %>%
    expression(knockdown/control) %>%
    export_analysis(knockdown/control, .analysis = "expression") %>% 
    left_join(hela_proteins %>%  export_quant() %>% select(matches("protein|abundance")), 
              by = hela_proteins$identifier)
```

**Comment by jeffsocal** [comment]
I added this functionality to v1.6.1, which will automatically output the abundance data in columns for each sample.
